version: '3'

services:
  app:
    container_name: admission-hub
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: main.py
      SECRET_KEY: "@admission-hub@"
    networks:
      - network-admission-hub
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: admissions
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

networks:
  network-admission-hub:
    driver: bridge